export { RoomsList } from './ui/RoomsList/RoomsList'
export { RoomForm } from './ui/RoomForm/RoomForm'
export { RoomSelect } from './ui/RoomSelect/RoomSelect'
export type { RoomSchema, Room } from './model/types/roomSchema'
export { setRooms } from './model/slice/roomSlice'
